# Set paths in a way that the program is always run from root i.e Machine Learning folder
MNIST_TRAIN = "Input/MNIST/mnist_train.csv"
MNIST_TRAIN_FOLDS = "Input/MNIST/mnist_train_folds.csv"
MNIST_MODEL_OUTPUT = "Models/MNIST/"
CAT_DAT_TRAIN = "Input/Cat_in_Dat/train.csv"
CAT_DAT_TRAIN_FOLD = "Input/Cat_in_Dat/train_folds.csv"
CENSUS_TRAIN = "Input/US_Adult_Census/adult.csv"
CENSUS_TRAIN_FOLD = "Input/US_Adult_Census/adult_fold.csv"
MOBILE_TRAIN = "Input/Mobile_Price/train.csv"
MOBILE_TEST = "Input/Mobile_Price/test.csv"
